[cat.Coreutils]
name = "cat (Coreutils)"
desc = "Concatenate and write files"

[cfs]
name = "CFS"
desc = "Completely Fair Scheduler"
more = "A process scheduler that was merged into the Linux kernel 2.6.23 (October 2007) and is the default scheduler of the tasks of the SCHED_NORMAL class (i.e., tasks that have no real-time execution constraints)."

[cdbs.Debian]
name = "cdbs"
desc = "Common Debian Build System"

[cgroup]
name = "cgroup"
desc = "Control Group"
more = "A Linux kernel feature for organizing processes and managing their resource usage (CPU, memory, I/O, etc.)"
