[eagain]
name = "EAGAIN"
desc = "Resource temporarily unavailable.  This is a temporary condition and later calls to the same routine may complete normally."

[esrch]
name = "ESRCH"
desc = "No process or process group can be found corresponding to that specified by pid"
more = "Please refer to kill() system call"

[execlp]
name = "execlp"

[eopkg]
name = "eopkg"
desc = "EvolveOS package"
more = "It is the package manager for the Solus operating system, originally from Pardus Linux, and adapted/maintained during the lifetime of SolusOS, EvolveOS and Solus"

[eevdf]
name = "EEVDF"
desc = "Earliest Eligible Virtual Deadline First"
