[fwupd]
name = "fwupd"
desc = "Firmware Update daemon on Linux-based system"

[fuse]
name = "FUSE"
desc = "Filesystem in Userspace"
more = "A software interface for Unix and Unix-like computer operating systems that lets non-privileged users create their own file systems without editing kernel code. This is achieved by running file system code in user space while the FUSE module provides only a bridge to the actual kernel interfaces."

[f2fs]
name = "F2FS"
desc = "Flash-Friendly File System"

[fenv.Header]
name = "<fenv.h>"
desc = "Floating-point Environment"
