[fwupd]
name = "fwupd"
desc = "Firmware Update daemon on Linux-based system"

[fuse]
name = "FUSE"
desc = "Filesystem in Userspace"
more = "A software interface for Unix and Unix-like computer operating systems that lets non-privileged users create their own file systems without editing kernel code. This is achieved by running file system code in user space while the FUSE module provides only a bridge to the actual kernel interfaces."

[f2fs]
name = "F2FS"
desc = "Flash-Friendly File System"

[fenv.Header]
name = "<fenv.h>"
desc = "Floating-point Environment"

[freetds]
name = "FreeTDS"
desc = "Tabular Data Stream"
more = """A set of libraries for Unix and Linux that allows your programs to natively talk to Microsoft SQL Server and Sybase databases.

  An open source implementation of the TDS (Tabular Data Stream) protocol used by these databases for their own clients. It supports many different flavors of the protocol and three APIs to access it. Additionally FreeTDS works with other software such as Perl and PHP, providing access from those languages as well.
"""
