[genwqe]
name = "GenWQE"
desc = "Generic Work Queue Engine"
more = "It supports hardware-accelerated data compression and decompression through zEDC Express, a PCIe-attached Field Programmable Gate Array (FPGA) acceleration adapter."

[gid]
name = "gid"
desc = "group ID"

[getdents]
name = "getdents(2)"
desc = "get directory entries"

[gfp]
name = "GFP"
desc = "Get Free Pages"
