[initrd]
name = "initrd"
desc = "initial ramdisk"
more = "A scheme for loading a temporary root file system into memory, to be used as part of the Linux startup process. 'initrd' and 'initramfs' refer to two different methods of achieving this. Both are commonly used to make preparations before the real root file system can be mounted."
