[initrd]
name = "initrd"
desc = "initial ramdisk"
more = "A scheme for loading a temporary root file system into memory, to be used as part of the Linux startup process. 'initrd' and 'initramfs' refer to two different methods of achieving this. Both are commonly used to make preparations before the real root file system can be mounted."

[irix]
name = "IRIX"
desc = "IRIS UNIX"
more = "IRIS was SGI's workstation series name at the time of IRIX's release. A discontinued operating system developed by Silicon Graphics (SGI) to run on the company's proprietary MIPS workstations and servers. It is based on UNIX System V with BSD extensions. In IRIX, SGI originated the XFS file system and the industry-standard OpenGL graphics system."
