[nl.Coreutils]
name = "nl (Coreutils) "
desc = "Number lines and write files"

[nm.Binutils]
name = "nm (Binutils)"
desc = "name"
more = "List symbols' names exported by object file"

[nproc.Coreutils]
name = "nproc (Coreutils) "
desc = "number of processors"

[nc]
name = "nc"
desc = "netcat"

[nftw]
name = "nftw()"
same = "ftw()=>ftw"
