[pwd.Coreutils]
name = "pwd (Coreutils) "
desc = "Print Working Directory"

[ps.POSIX]
name = "ps"
desc = "Process Status"
more = "Note: It doesn't belong to coreutils"

[pcb]
name = "PCB"
desc = "Process Control Block"

[ptrace]
name = "ptrace() syscall"
desc = "process trace"
see = 'strace'

[printk]
name = "printk()"
desc = "prints messages to the Kernel log"

[prlimit]
name = "prlimit(2)"
desc = "process resource limit"
more = "The Linux-specific prlimit() system call combines and extends the functionality of setrlimit() and getrlimit().  It can be used to both set and get the resource limits of an arbitrary process."

[perf]
name = "perf"
desc = "performance analyzing tool in Linux"

[pty]
name = "pty"
desc = "pseudo teletype"
see = ['tty', 'pts', 'ptmx']

[pts]
name = "pts"
desc = "pseudo teletype, the slave part"
see = ['ptmx', 'pty', 'tty']

[ptmx]
name = "/dev/ptmx"
desc = "pseudo teletype master x"
more = "A character file. When a process opens /dev/ptmx, it gets a file descriptor for a pseudoterminal master (PTM), and a pseudoterminal slave (PTS) device is created in the /dev/pts directory. Each file descriptor obtained by opening /dev/ptmx is an independent PTM with its own associated PTS, whose path can be found by passing the descriptor to ptsname(3)."
