[pwd.Coreutils]
name = "pwd (Coreutils) "
desc = "Print Working Directory"

[ps.POSIX]
name = "ps"
desc = "Process Status"
more = "Note: It doesn't belong to coreutils"

[pcb]
name = "PCB"
desc = "Process Control Block"

[ptrace]
name = "ptrace() syscall"
desc = "process trace"
see = 'strace'

[printk]
name = "printk()"
desc = "prints messages to the Kernel log"

[prlimit]
name = "prlimit(2)"
desc = "process resource limit"
more = "The Linux-specific prlimit() system call combines and extends the functionality of setrlimit() and getrlimit().  It can be used to both set and get the resource limits of an arbitrary process."

[perf]
name = "perf"
desc = "performance analyzing tool in Linux"
