[xfce]
name = "Xfce"
desc = "XForms Common Environment or X Freakin' Cool Environment"

[xopen]
name = "X/Open"
desc = "Open Group for Unix Systems"
more = """A consortium founded by several European UNIX systems manufacturers in 1984 to identify and promote open standards.

In 1993, a planned transfer of UNIX trademark from Novell to X/Open was announced.

In 1994, X/Open published the Single UNIX Specification."""

[xcb]
name = "XCB"
desc = "X protocol C-language Binding"
more = "a library implementing the client-side of the X11 display server protocol, aims to replace Xlib"

[xkb]
name = "XKB"
desc = "X Keyboard Extension"
more = "A reduced subset of keymaps specification"
